influxdb:
  image: influxdb:1.2.2
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  volumes:
    - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    - /tmp/influxdb:/var/lib/influxdb

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  environment:
    - GF_SERVER_ROOT_URL=http://tk2-234-26849.vs.sakura.ne.jp/grafana
  ports:
    - "3000:3000"
  volumes:
    - /tmp/grafana:/var/lib/grafana
  links:
    - influxdb

nginx:
  image: nginx:latest
  container_name: nginx
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d/
  ports:
    - "80:80"
    - "443:443"
  links:
    - grafana
    - influxdb
